### ISSUE TITLE
License update

### ISSUE THREAD

**Issue by nsryan2** [arfc/moltres-init#1]
## I'm submitting a ...
  - [x] feature request

## Expected Behavior
There should be a LICENSE file that covers the entire repository.

## Actual Behavior
Currently, there is no License file covering the whole repository. 

My uncertainty with which License to give this repository is that other Moltres projects had LGPL Licenses, which are viral. This appears to be something that interacts with Moltres, but I can't ascertain if it is a direct derivative of the original program.

## How can this issue be closed?
First, a determination has to be made about the type of License under which to cover this repository.
Second, that License should then be added through a pull request to this repository.

**Comment by katyhuff** [comment]
This is mostly a paper directory. I don't think there's much code (double check). So, CC-BY.
